{
 "title": "BigBlueButton All Servers",
 "tags": [
  "BigBlueButton",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bbb_exporter, job)"
   },
   {
    "name": "job_node_exporter",
    "label": "Job node_exporter",
    "query": "label_values(node_cpu_seconds_total, job)"
   },
   {
    "name": "job_netdata",
    "label": "Job Netdata",
    "query": "label_values(netdata_system_cpu_percentage_average, job)"
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": "label_values(node_network_address_assign_type, device)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_api_up{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BigBlueButton Exporter Version",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "bbb_exporter{job=\"$job\"}",
     "legendFormat": "{{instance}} | {{version}}"
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bbb_meetings_participants{job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Rooms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bbb_room_participants_gcount{job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Participants per server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Rooms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Rooms" }
   ],
   "targets": [
    {
     "expr": "bbb_room_participants_gcount{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Participants by Client Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "sum(bbb_meetings_participant_clients{job=\"$job\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Max Participants for Selected Timeframe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Participants Origin",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants_origin{job=\"$job\"}",
     "legendFormat": "{{server}} - {{name}}"
    }
   ]
  },
  {
   "title": "CPU Utlization ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utlization [%]" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", job=\"$job_node_exporter\"}[5m])) by (instance)) * 100",
     "legendFormat": "{{instance}} (node_exporter)"
    },
    {
     "expr": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\", job=\"$job_netdata\"}) by (instance)",
     "legendFormat": "{{instance}} (Netdata)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job_node_exporter\"} - node_memory_MemAvailable_bytes{job=\"$job_node_exporter\"}) by (instance)",
     "legendFormat": "{{instance}} (node_exporter)"
    },
    {
     "expr": "(sum(netdata_system_ram_MiB_average{job=\"$job_netdata\"}) by (instance) - sum(netdata_mem_available_MiB_average{job=\"$job_netdata\"}) by (instance)) * 1024 * 1024",
     "legendFormat": "{{instance}} (Netdata)"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job_node_exporter\", device=\"$interface\"}[1m])*8",
     "legendFormat": "{{instance}} receive ({{device}}) (node_exporter)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job_node_exporter\", device=\"$interface\"}[1m])*8",
     "legendFormat": "{{instance}} sent ({{device}}) (node_exporteer)"
    },
    {
     "expr": "abs(netdata_net_net_kilobits_persec_average{job=\"$job_netdata\", family=\"$interface\"})",
     "legendFormat": "{{instance}} {{dimension}} ({{family}}) (Netdata)"
    }
   ]
  },
  { "title": "Recordings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Storage Utilization",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"$job_node_exporter\"} - node_filesystem_avail_bytes{job=\"$job_node_exporter\"}) / node_filesystem_size_bytes{job=\"$job_node_exporter\"}",
     "legendFormat": "{{instance}} ({{mountpoint}})"
    }
   ]
  },
  {
   "title": "Recordings Processing",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_processing{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Recordings Unprocessed",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_unprocessed{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Recordings Published",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_published{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Recordings Deleted",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_deleted{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Recordings Unpublished",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_unpublished{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Recordings Unprocessed",
   "type": "graph",
   "description": "Requires `RECORDINGS_METRICS_READ_FROM_DISK` to be enabled on the BigBlueButton Exporter",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Recordings " }
   ],
   "targets": [
    {
     "expr": "bbb_recordings_unprocessed{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Heatmaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Heatmap of Room Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_participants_bucket{job=\"$job\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Listeners Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of listeners while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_listeners_bucket{job=\"$job\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Voice Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of voice participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_voice_participants_bucket{job=\"$job\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Video Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of video participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_video_participants_bucket{job=\"$job\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Metrics Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\"}[5m])) by (le, instance, endpoint, parameters))) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BigBlueButton API Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "s", "label": "Resonse Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getMeetings\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=processing\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=processed\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=published\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=unpublished\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=deleted\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings deleted"
    }
   ]
  }
 ]
}