{
 "title": "BigBlueButton Server Instance (netdata)",
 "tags": [
  "BigBlueButton",
  "prometheus",
  "netdata"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bbb_api_up, instance)"
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": "label_values(netdata_net_net_kilobits_persec_average, family)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "bbb_api_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "BigBlueButton Exporter Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "bbb_exporter" }
   ]
  },
  {
   "title": "Type of Users Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    },
    {
     "expr": "bbb_meetings_listeners{instance=\"$instance\"}",
     "legendFormat": "Listeners"
    },
    {
     "expr": "bbb_meetings_voice_participants{instance=\"$instance\"}",
     "legendFormat": "Voice"
    },
    {
     "expr": "bbb_meetings_video_participants{instance=\"$instance\"}",
     "legendFormat": "Video"
    }
   ]
  },
  {
   "title": "CPU Utilization vs. Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utlization [%]" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\", instance=\"$instance\"})",
     "legendFormat": "CPU Utlization"
    },
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants{instance=\"$instance\"}",
     "legendFormat": "Voice participants"
    }
   ]
  },
  {
   "title": "Max Participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max(bbb_meetings_participants{instance=\"$instance\"})",
     "legendFormat": "Selected timeframe"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{instance=\"$instance\"}[1w])",
     "legendFormat": "Since 1 week"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{instance=\"$instance\"}[100y])",
     "legendFormat": "All time"
    }
   ]
  },
  {
   "title": "Bandwidth vs. Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "Kbits", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "abs(netdata_net_net_kilobits_persec_average{instance=\"$instance\", family=\"$interface\"})",
     "legendFormat": "{{family}} ({{dimension}})"
    },
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants{instance=\"$instance\"}",
     "legendFormat": "Video participants"
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "bbb_recordings_processing{instance=\"$instance\"}",
     "legendFormat": "Processing"
    },
    {
     "expr": "bbb_recordings_processed{instance=\"$instance\"}",
     "legendFormat": "Processed"
    },
    {
     "expr": "bbb_recordings_published{instance=\"$instance\"}",
     "legendFormat": "Published"
    },
    {
     "expr": "bbb_recordings_unpublished{instance=\"$instance\"}",
     "legendFormat": "Unpublished"
    },
    {
     "expr": "bbb_recordings_deleted{instance=\"$instance\"}",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Number of Rooms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Rooms" }
   ],
   "targets": [
    {
     "expr": "bbb_room_participants_gcount{instance=\"$instance\"}",
     "legendFormat": "Rooms"
    }
   ]
  },
  {
   "title": "Participants by Client Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participant_clients{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Heatmaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Heatmap of Room Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "bbb_room_participants_bucket{instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Listeners Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of listeners while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "bbb_room_listeners_bucket{instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Voice Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of voice participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "bbb_room_voice_participants_bucket{instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Video Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of video participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "bbb_room_video_participants_bucket{instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Metrics Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{instance=\"$instance\"}[5m])) by (le, instance, endpoint, parameters))) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API 95-th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Latency [s]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getMeetings\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=processing\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=processed\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=published\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=unpublished\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=deleted\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings deleted"
    }
   ]
  }
 ]
}