{
 "title": "BigBlueButton All Servers",
 "tags": [
  "BigBlueButton",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    { "expr": "bbb_api_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    { "expr": "bbb_meetings_participants", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Max Participants for Selected Timeframe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    { "expr": "bbb_meetings_participants", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "targets": [
    { "expr": "bbb_meetings_participants", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "targets": [
    { "expr": "bbb_meetings_listeners", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Recordings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Recordings Processing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "targets": [
    { "expr": "bbb_recordings_processing", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recordings Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "targets": [
    { "expr": "bbb_recordings_processed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recordings Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "targets": [
    { "expr": "bbb_recordings_published", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recordings Unpublished",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "targets": [
    { "expr": "bbb_recordings_unpublished", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recordings Deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "targets": [
    { "expr": "bbb_recordings_deleted", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "API 95-th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Latency [s]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getMeetings\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=processing\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=processed\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=published\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=unpublished\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=deleted\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings deleted"
    }
   ]
  }
 ]
}