{
 "title": "BigBlueButton",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "bbb_api_up" }
  ]
 },
 "panels": [
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bbb_meetings_participants", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "bbb_api_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Listeners total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "targets": [
    { "expr": "bbb_meetings_listeners", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Voice participants",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Video participants",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recordings processing",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "targets": [
    { "expr": "bbb_recordings_processing", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recordings processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "targets": [
    { "expr": "bbb_recordings_processed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recordings published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "targets": [
    { "expr": "bbb_recordings_published", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recordings unpublished",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "targets": [
    { "expr": "bbb_recordings_unpublished", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recordings deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "targets": [
    { "expr": "bbb_recordings_deleted", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "API 95-th percentile latency for $instance",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getMeetings\", instance=\"$instance\"}[5m])) by (le))",
     "legendFormat": "getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", instance=\"$instance\", parameters=\"state=processing\"}[5m])) by (le))",
     "legendFormat": "getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", instance=\"$instance\", parameters=\"state=processed\"}[5m])) by (le))",
     "legendFormat": "getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", instance=\"$instance\", parameters=\"state=published\"}[5m])) by (le))",
     "legendFormat": "getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", instance=\"$instance\", parameters=\"state=unpublished\"}[5m])) by (le))",
     "legendFormat": "getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", instance=\"$instance\", parameters=\"state=deleted\"}[5m])) by (le))",
     "legendFormat": "getRecordings deleted"
    }
   ]
  }
 ]
}