name: Docker image build on tag
on: push

jobs:
  build:
    name: Push Docker image to GitHub package container registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: greenstatic/bigbluebutton-exporter
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
